- name: Debug shell command
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    shell_commands:
      - echo "No command specified"
  tasks:
    - name: Run custom shell command
      ansible.builtin.shell:
        cmd: "{{ item }}"
      loop: "{{ shell_commands }}"
      register: shell_commands_output

    - debug:
        msg:
          stdout: "{{ item.stdout_lines }}"
          stderr: "{{ item.stderr_lines }}"
      loop_control:
        label: item.cmd
      loop: "{{ shell_commands_output.results }}"
